name: Generate Database Types

inputs:
  SUPABASE_ACCESS_TOKEN:
    required: true
    description: "SUPABASE_ACCESS_TOKEN"
  SUPABASE_PROJECT_ID:
    required: true
    description: "SUPABASE_PROJECT_ID"
  GITHUB_TOKEN:
    required: true
    description: "GITHUB_TOKEN"

on:
    workflow_call:
    push:
        paths:
            - "db/**"
        branches:
            - main
runs:
    using: "composite"
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Cache node modules
          id: cache-modules
          uses: actions/cache@v3
          with:
              path: db/node_modules
              key: node_modules-${{ runner.os }}-db-${{hashFiles('db/package-lock.json')}}
              restore-keys: node_modules-${{ runner.os }}-db-

        - name: Install dependencies
          if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
          run: npm install
          shell: bash

        - name: Login to Supabase
          run: npx supabase login --token ${{ inputs.SUPABASE_ACCESS_TOKEN }}
          shell: bash

        - name: Build types
          run: |
              npx supabase gen types typescript --project-id ${{ inputs.SUPABASE_PROJECT_ID }} --schema public > ./db/database.types.ts
              cd db && ./autogen.sh && cd ..
          shell: bash

        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
              commit_message: "bot(db): generate database types"
              token: ${{ inputs.GITHUB_TOKEN }}

