version: "1.1"
name: Status Check
tests:
    healthcheck:
        steps:
            - name: GET request
              http:
                  url: ${{env.origin}}/api/test
                  method: GET
                  check:
                      status: /^20/
    storage:
        steps:
            - name: PUT request
              http:
                  url: ${{env.origin}}/api/v1/storage/upload
                  method: PUT
                  json:
                      fileName: "test.txt"
                  check:
                      status: /^20/
                      headers:
                          Content-Type: application/json
                      schemaa:
                          type: object
                          properties:
                              signedPUTURL:
                                  type: string
                              downloadURL:
                                  type: string
                          required:
                              - signedPUTURL
                              - downloadURL
