#!/bin/bash

# Ignore on Windows
if [[ "$(uname)" == "WindowsNT" ]]; then
  exit 0;
fi

ALL_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

if [ -z "$ALL_FILES" ]; then
  exit 0
fi

# Check if prettier is installed otherwise npm install
npm list > /dev/null 2>&1 || npm install
npm list --depth=0 | egrep 'prettier' > /dev/null 2>&1 || npm install --save-dev prettier
npm list --depth=0 | egrep 'prettier-plugin-tailwindcss'> /dev/null 2>&1 || npm install --save-dev prettier-plugin-tailwindcss

# echo "Prettifying web files..."
npx prettier $(echo $ALL_FILES | egrep '\<web/') --write --ignore-unknown --config ./web/.prettierrc

# echo "Prettifying mobile files..."
npx prettier $(echo "$ALL_FILES" | egrep '\<mobile/') --write --ignore-unknown --config ./mobile/.prettierrc

git add $ALL_FILES

exit 0