name: Generate Database Types
env:
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
on:
    push:
        paths:
            - "db/**"
        branches:
            - main
jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
            contents: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Cache node modules
              id: cache-modules
              uses: actions/cache@v3
              with:
                  path: db/node_modules
                  key: node_modules-${{ runner.os }}-db-${{hashFiles('db/package-lock.lock')}}
                  restore-keys: node_modules-${{ runner.os }}-db-

            - name: Install dependencies
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: npm install

            - name: Login to Supabase
              run: npx supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

            - name: Build types
              run: |
                npx supabase gen types typescript --project-id ${{ secrets.SUPABASE_PROJECT_ID }} --schema public > ./db/database.types.ts
                ./db/autogen.sh

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: 'bot(db): generate database types'
