name: Database

env:
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

on:
    workflow_dispatch:
    workflow_call:

jobs:
    Update-Types:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./db
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Extract branch name
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
              id: extract_branch

            - name: Cache node modules
              id: cache-modules
              uses: actions/cache@v3
              with:
                  path: |
                    **/node_modules
                    ~/.npm
                  key: node_modules-${{ runner.os }}-db-${{hashFiles('package-lock.json')}}
                  restore-keys: node_modules-${{ runner.os }}-db-

            - name: Install dependencies
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: npm ci
              shell: bash

            - name: Login to Supabase
              run: npx supabase login --token=${{ secrets.SUPABASE_ACCESS_TOKEN }}

            - name: Build types
              run: |
                  npx supabase gen types typescript --project-id ${{ steps.extract_branch.outputs.branch == 'main' && secrets.PROD_SUPABASE_PROJECT_ID || secrets.DEV_SUPABASE_PROJECT_ID }} --schema public > ./database.types.ts
                  ./autogen.sh
              shell: bash

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "bot(db): generate database types"
