name: Vercel Production Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        paths:
            - "web/**"
        branches:
            - main

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  sparse-checkout: "web"

            - name: Cache node modules
              uses: actions/cache@v3
              id: cache-modules
              with:
                  path: web/node_modules
                  key: node_modules-${{ runner.os }}-deploy-${{hashFiles('web/package-lock.json')}}
                  restore-keys: node_modules-${{ runner.os }}-deploy-

            - uses: dorny/paths-filter@v3
              id: db-changes
              with:
                  filters: |
                      db:
                        - 'db/**'

            - name: Run Database Types Generation
              if: ${{ steps.db-changes.outputs.db == 'true' }}
              uses: ./.github/workflows/database-types.yaml

            - name: Install Vercel CLI
              if: ${{ steps.cache-modules.outputs.cache-hit != 'true' }}
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: |
                  msg=`vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}`
                  echo "::notice title={[Production] Deployed on Vercel}::$msg"
