name: Vercel Preview Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        paths:
            - "web/**"
        branches-ignore:
            - main
jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  sparse-checkout: "web"

            - name: Cache node modules
              uses: actions/cache@v3
              id: cache-modules
              with:
                  path: web/node_modules
                  key: node_modules-${{ runner.os }}-preview-${{hashFiles('web/package-lock.lock')}}
                  restore-keys: node_modules-${{ runner.os }}-preview-

            - name: Install Vercel CLI
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: |
                  msg=`vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --prebuilt`
                  echo "::notice title={[Preview] Deployed on Vercel}::$msg"
