name: Vercel Preview Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    workflow_dispatch:
    push:
        paths:
            - "web/**"
        branches-ignore:
            - main
jobs:
    Deploy-Preview:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Cache node modules
              uses: actions/cache@v3
              id: cache-modules
              with:
                  path: |
                    web/node_modules
                    ~/.npm
                  key: node_modules-${{ runner.os }}-preview-${{hashFiles('web/package-lock.json')}}
                  restore-keys: node_modules-${{ runner.os }}-preview-

            - uses: dorny/paths-filter@v3
              id: db-changes
              with:
                  filters: |
                      db:
                        - 'db/**'

            - name: Run Database Types Generation
              if: steps.db-changes.outputs.db == 'true'
              uses: ./.github/actions/database-types
              with:
                SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
                SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

            - name: Install Vercel CLI
              if: steps.cache-modules.outputs.cache-hit != 'true'
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
              timeout-minutes: 2

            - name: Deploy Project Artifacts to Vercel
              run: |
                  msg=`vercel deploy --token=${{ secrets.VERCEL_TOKEN }} --prebuilt`
                  echo "::notice title={[Preview] Deployed on Vercel}::$msg"
              timeout-minutes: 2
